@startuml Modelo_dominio_conecta4
title Modelo de dominio <b>conecta4</b>\n

Conecta4 *-down-> Board
Conecta4 *-down-> Turn

Turn -down-> "2" Player
Turn -down-> Board

Player -down-> Board
Player o-down-> "0..21" Chip
Player o-down-> Goal
Player o-down-> Color

Chip o-down-> Color

enum Color {
  BLUE
  RED
  NULL
}

Goal .down.> Board
Goal .down.> Coordinate

Board *-down-> "7" Column
Column *-down-> "6" Place
Column ..down-> Coordinate

Place *-down-> Coordinate
Place o-down-> "1" Chip

Goal <|-down- RowWinner
Goal <|-down- ColumnWinner
Goal <|-down- MainDiagonalWinner
Goal <|-down- InvertedDiagonalWinner

@enduml